Adds Github recommended supporting docs
WordPress/Marketing-Team pull request #211
Opened 2023-04-03 21:39 UTC by eidolonnight

This adds code_of_conduct.md, contributing.md, and support.md files to the Marketing Team repo. These are recommended pages outlined under the [Building communities](https://docs.github.com/en/communities) Github documentation, and these should aid in directing new contributors to various resources. Links appear in various places within the team repository, including the sidebar when submitting new issues.

This initial commit creates basic pages with links to the handbook and other resources.

2023-04-03 21:41 UTC, eidolonnight commented
This pull request is the first half of work toward https://github.com/WordPress/Marketing-Team/issues/140

2023-04-03 23:51 UTC, sereedmedia commented
Hi, thanks for tagging me! My comments:

- There is an existing WordPress Code of Conduct. _I am not okay with the Marketing Team adopting a unique Code of Conduct._ Emphasis for emphasis. That is not something that can be maintained **or enforced** properly by the Marketing Team. Any Code of Conduct referenced or developed should apply project-wide. If we feel that we need a more specific Code of Conduct for contribution than what is covered in the existing WordPress Code of Conduct, then that is something we should bring up with the Community Team or discuss in the Team Reps channel.
- The handbook link in Support resources is not linking properly. 
- I think linking back to the official WordPress.org site and marketing team handbook as you have done with the contributing and support pages is the best way to handle all of these docs, including (especially) the Code of Conduct. AFAIK, the Make Team Handbooks are currently the "single source of truth" for WordPress contribution.

2023-04-04 00:27 UTC, sereedmedia requested changes
Cannot approve with the code of conduct text included.

2023-04-04 00:27 UTC, sereedmedia commented on .github/support.md
> +Documentation for the Marketing Team can be found in the [handbook][Link](https://make.wordpress.org/marketing/handbook/about/), and questions are best directed to the [#marketing Slack channel](http
```suggestion
Documentation for the Marketing Team can be found in the [handbook] https://make.wordpress.org/marketing/handbook/about/), and questions are best directed to the [#marketing Slack channel](https://wordpress.slack.com/archives/C0GKJ7TFA).
```

2023-04-04 00:29 UTC, sereedmedia commented
Did an official review, but the same comments as my original. Redundancy is good for everyone and everybody!

2023-04-04 15:29 UTC, eidolonnight commented on code_of_conduct.md
From [Slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1680558625031919):

> Thanks so much! So for the code of conduct, that is simply a copy of the coc from https://make.wordpress.org/handbook/community-code-of-conduct/ (I very much agree that we should not have a separate coc).

> I chose to copy it and link the original because when someone clicks the link in github it seemed inconvenient to make them click another link.

> As for maintaining parity, the coc doesn't change often, so I figured it wasn't a big deal in this case.
What do you think? Strip it to just a link to the coc and accept the sub-par user experience? Keep it and update the preamble to make clear that this is a copy, accepting that it will maybe need to be updated each year?

> None of this is written in stone, so I'm fine with either approach.

If there are no dissenting opinions. I'll update the file to remove the coc copy.

2023-04-06 20:21 UTC, sereedmedia approved these changes
Looks good to me, thanks for using the direct link.

2023-04-11 19:05 UTC, sereedmedia commented
@jpantani can you review so we can get this closed and posted? it's super basic content.

2023-04-12 21:28 UTC, jpantani approved these changes
Everything looks good on my end.

2023-04-25 15:43 UTC, merged